### ISSUE TITLE
Question: Trying to install tailwindcss nesting

### ISSUE THREAD

**Issue by ineptian** [yhaefliger/YATAS#1]
Have had a fun time working with this starter so far. One thing I cannot figure out is how to implement nesting since you are using the tailwind cli and not post css. Any easy way to get that enabled in here? Thanks!

**Comment by yhaefliger** [comment]
Hello! Glad your having fun with this starter ☺️
As far as I know Tailwind cli uses postcss under the hood.
To customize the plugins it uses just put a `postcss.config.js` file at the root of the project.

Tailwind ships with his postcss nesting plugin `tailwindcss/nesting `. To use it wit other recommended plugins
```
// postcss.config.js
module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss/nesting'),
    require('tailwindcss'),
    require('autoprefixer'),
  ]
}
```
If you keep this config just `npm install -D postcss-import ` other modules are bundled with Tailwind 👍

**Comment by ineptian** [comment]
Thanks for the quick reply. I had the postcss config in there, but I never installed postcss-import. Wondering if that was the issue. Going to do that now and I will let you know if that works.

**Comment by ineptian** [comment]
Ok so I added the postcss.config.js, and installed postcss-import, but it still does not work. You can see when you inspect the styles that it doesn't generate the nested styles.

The only hint I have is that VSC is telling me that:
```
Could not find a declaration file for module 'tailwindcss/nesting'. 'D:/Work/Coast to Coast Advertising/website/coast-to-coast-yatas/node_modules/tailwindcss/nesting/index.js' implicitly has an 'any' type.
```

Any ideas? Its not a huge deal but at this point I just really want to figure out why it wont work!

Thanks

**Comment by yhaefliger** [comment]
Strange I thought it needed nothing else but I am maybe missing something I'll check on my pc tomorrow 🤔
Meanwhile can you maybe share the content of your `package-lock.json` so I can check all the modules and versions installed on your project?
Thanks.

**Comment by ineptian** [comment]
Sure thing. The cross-env package is because I am on windows and afaik adding that in is the only way for tailwind to work.
It is too long to paste in here and github wont let me upload a json file so I am just uploading it as plain text. Let me know if you need anything else. Thanks a bunch for being responsive on this!

[package-lock.txt](https://github.com/yhaefliger/YATAS/files/7836385/package-lock.txt)
!

**Comment by yhaefliger** [comment]
Found it!
You also need to put the flag `--postcss` in the `package.json` for watch-css and build-css scripts:

```
"watch-css": "npx tailwindcss --postcss -i ./assets/css/styles.css -o ./_site/css/styles.css -w",
"build-css": "npx tailwindcss --postcss -i ./assets/css/styles.css -o ./_site/css/styles.css --minify",
```

Worked for me, hope it will on your project too :)

**Comment by ineptian** [comment]
Let's go!!! That was it. Thanks for the help!
